# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: [ master ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }}/developers-sdk-kt # location for the settings.xml file

      - name: Build with Gradle
        run: ./developers-sdk-kt/gradlew assemble

      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish to maven central repository
        run: ./developers-sdk-kt/gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish to bintray(jcenter) repository
        run: ./developers-sdk-kt/gradlew bintryUpload
        env:
          BINTRAY_USERNAME: ${{ secrets.BIN_TRAY_USRE_NAME }}
          BINTRAY_KEY: ${{ secrets.BIN_TRAY_API_KEY }}
